/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Feature: typeof import('./src/components/feature.vue')['default']
    Grid: typeof import('./src/components/grid.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Page: typeof import('./src/components/page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Teaser: typeof import('./src/components/teaser.vue')['default']
  }
}
